services:
  astro:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - "./docs:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
