# Site Settings
title: Blankie
description: >-
  Ambient sound mixer for macOS

# Build settings
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
