name: Extract Localization Files to Separate Branch

on:
  push:
    paths:
      - "**/*.xcstrings"
      - ".github/workflows/blanki8n.yml"
      - ".github/scripts/extract-strings.js"
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install glob

      - name: Run extraction
        run: |
          mkdir -p i18n
          node .github/scripts/extract-strings.js --globs "Blankie/*.xcstrings" --output-dir "i18n"

          echo "--- Extraction Results ---"
          echo "Generated files:"
          ls -la i18n/
          echo "------------------------"

      - name: Deploy to i18n branch
        run: |
          # Configure git
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create and checkout an orphan branch (no history)
          git checkout --orphan i18n-data

          # Remove everything
          git rm -rf .

          # Move only the specific JSON files to the root 
          # (excluding extracted.json, package.json, and package-lock.json)
          mkdir -p temp
          find i18n -name "*.json" \
            -not -name "extracted.json" \
            -not -name "package.json" \
            -not -name "package-lock.json" \
            -exec cp {} temp/ \;

          # Create a README
          echo "# Blankie Localization Files" > temp/README.md
          echo "" >> temp/README.md
          echo "This branch contains the localization JSON files for Blankie app. These files are automatically generated from .xcstrings files." >> temp/README.md
          echo "" >> temp/README.md
          echo "Last updated: $(date)" >> temp/README.md

          # Add translation statistics to README if summary.txt exists
          if [ -f i18n/summary.txt ]; then
            echo "" >> temp/README.md
            echo "## Translation Status" >> temp/README.md
            echo "" >> temp/README.md
            cat i18n/summary.txt >> temp/README.md
          fi

          # Move the files from temp to root
          mv temp/* .
          rmdir temp

          # Stage only the JSON files and README
          git add *.json README.md

          # Commit with the summary message if it exists
          if [ -f i18n/summary.txt ]; then
            git commit -m "$(cat i18n/summary.txt)"
          else
            git commit -m "Update localization data [skip ci]"
          fi

          # Force push to the i18n-data branch
          git push -f origin i18n-data

          echo "Localization files pushed to i18n-data branch"
