name: Update Credits

on:
  push:
    paths:
      - "Blankie/credits.json"
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-credits:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Generate translator credits
        run: |
          mkdir -p temp
          ./scripts/GenerateCreditsBlock.swift temp/translators.md

      - name: Ensure we have working directory
        run: mkdir -p .github/actions

      - name: Create updater script
        run: |
          cat > .github/actions/update_section.sh << 'EOF'
          #!/bin/bash

          README="README.md"
          TEMP_FILE="README.md.new"
          START_MARKER="<!-- TRANSLATOR_CREDITS_START -->"
          END_MARKER="<!-- TRANSLATOR_CREDITS_END -->"
          CONTENT_FILE="temp/translators.md"
          skip=false

          # Read the content in chunks
          while IFS= read -r line; do
            if [[ "$line" == *"$START_MARKER"* ]]; then
              # Found start marker - output it
              echo "$line" >> "$TEMP_FILE"
              
              # Insert the new content
              cat "$CONTENT_FILE" >> "$TEMP_FILE"
              
              # Skip lines until end marker
              skip=true
            elif [[ "$line" == *"$END_MARKER"* ]]; then
              # Found end marker - output it and stop skipping
              echo "$line" >> "$TEMP_FILE"
              skip=false
            elif [[ "$skip" != "true" ]]; then
              # Not skipping, so output the line
              echo "$line" >> "$TEMP_FILE"
            fi
          done < "$README"

          # Replace the original file
          mv "$TEMP_FILE" "$README"
          EOF

          chmod +x .github/actions/update_section.sh

      - name: Update translator credits in README
        run: |
          # Run the script
          .github/actions/update_section.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update translator credits in README"
          title: "Update translator credits in README"
          body: |
            Automated PR to update translator credits in README.

            This PR was automatically generated by the Update Credits workflow.
          branch: update-translator-credits
          base: main
          delete-branch: true
          labels: |
            automated-pr
            documentation
